#!/usr/bin/env bash
set -euo pipefail

rm -rf     "$HOME/.themes/Aerobird"     "$HOME/.themes/Aerobird-Blue"     "$HOME/.icons/Windows-7"     "$HOME/.icons/Win2-7"     "$HOME/.icons/Win2-7Libre"     "$HOME/.icons/aero-drop"     "$HOME/.local/share/sounds/Win2-7"     "$HOME/.local/share/backgrounds/win2-7-nostalgia"

STATE_DIR="$HOME/.config/win2-7-nostalgia"
STATE_FILE="$STATE_DIR/xfce-before-install"
WALLPAPER_STATE="$STATE_DIR/wallpapers-before"

if [ -f "$STATE_FILE" ] && command -v xfconf-query >/dev/null 2>&1; then
    # This file is generated by install.sh using shell-escaped values only.
    source "$STATE_FILE"
    [ -z "${GTK_THEME:-}" ] || xfconf-query -c xsettings -p /Net/ThemeName -s "$GTK_THEME"
    [ -z "${ICON_THEME:-}" ] || xfconf-query -c xsettings -p /Net/IconThemeName -s "$ICON_THEME"
    [ -z "${CURSOR_THEME:-}" ] || xfconf-query -c xsettings -p /Gtk/CursorThemeName -s "$CURSOR_THEME"
    [ -z "${XFWM_THEME:-}" ] || xfconf-query -c xfwm4 -p /general/theme -s "$XFWM_THEME"
fi

if [ -f "$WALLPAPER_STATE" ] && command -v xfconf-query >/dev/null 2>&1; then
    while IFS=
echo "Win2-7 Nostalgia Edition removed. Angujanú themes were preserved."
\t' read -r property value; do
        [ -z "$property" ] || xfconf-query -c xfce4-desktop -p "$property" -s "$value" 2>/dev/null || true
    done < "$WALLPAPER_STATE"
    command -v xfdesktop >/dev/null 2>&1 && xfdesktop --reload >/dev/null 2>&1 || true
fi

rm -rf "$STATE_DIR"
echo "Win2-7 Nostalgia Edition removed. Angujanú themes were preserved."
