
[Desktop Entry]
Name=Win2-7Darth Vader
Type=X-GNOME-Metatheme
Comment=Inspired on Win2-7 

Name[es_ES]=Win2-7Darth-Vader

[X-GNOME-Metatheme]
GtkTheme=Win2-7Darth-Vader
MetacityTheme=Win2-7Darth-Vader
IconTheme=Win2-7
CursorTheme=aero-drop
CursorSize=18
ButtonLayout=menu:minimize,maximize,close

#Fonts
ApplicationFont=Segoe UI 10
DocumentFont=Segoe UI 10
DesktopFont=Segoe UI 10
WindowTitleFont=Segoe UI 10
FixedWidthFont=Monospace 10
